# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aq8pBOMMG00ZqqHAiQIi-SHIbURmeyKS
"""

def birhaftalik_menyu(belgi):
 if belgi== "Dushanba":
  return "No'xot sho'rva"
 elif belgi== "Seshanba":
    return "Manti"
 elif belgi== "Chorshanba":
      return "Qovurma lag'mon"
 elif belgi== "Payshanba":
       return "Mastava"
 elif belgi== "Juma":
       return "Somsa"
 elif belgi== "Shanba":
       return "Qozon kabob"
 elif belgi== "Yakshanba":
       return "Palov"
 else:
        return "boshqa menyuni tanlang"
belgi=input("Hafta kunini kiriting")
natija=birhaftalik_menyu(belgi)
print(natija)